package com.dephoegon.delbase.aid.event;

import com.dephoegon.delbase.aid.block.colorshift.fence.*;
import com.dephoegon.delbase.aid.block.colorshift.slab.*;
import com.dephoegon.delbase.aid.block.colorshift.stair.*;
import com.dephoegon.delbase.aid.block.colorshift.wall.*;
import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.item.Item;
import net.minecraft.util.ActionResult;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

import static com.dephoegon.delbase.aid.util.blockArrayList.*;
import static com.dephoegon.delbase.aid.util.colorMixInteractions.ColorLogic;
import static com.dephoegon.delbase.block.axis.axisCutSandStones.*;
import static com.dephoegon.delbase.block.fence.chiseledSandStoneFences.*;
import static com.dephoegon.delbase.block.fence.concreteFences.*;
import static com.dephoegon.delbase.block.fence.cutSandStoneFence.*;
import static com.dephoegon.delbase.block.fence.sandFences.*;
import static com.dephoegon.delbase.block.fence.sandStoneFences.*;
import static com.dephoegon.delbase.block.fence.smoothSandStoneFences.*;
import static com.dephoegon.delbase.block.fence.terracottaFences.*;
import static com.dephoegon.delbase.block.general.genChiseledSandStones.*;
import static com.dephoegon.delbase.block.general.genSandStones.*;
import static com.dephoegon.delbase.block.general.genSmoothSandStones.*;
import static com.dephoegon.delbase.block.gravity.gravColorSands.*;
import static com.dephoegon.delbase.block.gravity.gravColorSolidSand.*;
import static com.dephoegon.delbase.block.slabs.slabChiseledSandStones.*;
import static com.dephoegon.delbase.block.slabs.slabChiseledSandStonesEnergy.*;
import static com.dephoegon.delbase.block.slabs.slabConcrete.*;
import static com.dephoegon.delbase.block.slabs.slabCutSandStones.*;
import static com.dephoegon.delbase.block.slabs.slabCutSandStonesEnergy.*;
import static com.dephoegon.delbase.block.slabs.slabSandStones.*;
import static com.dephoegon.delbase.block.slabs.slabSandStonesEnergy.*;
import static com.dephoegon.delbase.block.slabs.slabSands.*;
import static com.dephoegon.delbase.block.slabs.slabSandsEnergy.*;
import static com.dephoegon.delbase.block.slabs.slabSmoothSandStones.*;
import static com.dephoegon.delbase.block.slabs.slabSmoothSandStonesEnergy.*;
import static com.dephoegon.delbase.block.slabs.slabTerracotta.*;
import static com.dephoegon.delbase.block.stair.stairChiseledSandStones.*;
import static com.dephoegon.delbase.block.stair.stairConcrete.*;
import static com.dephoegon.delbase.block.stair.stairCutSandStones.*;
import static com.dephoegon.delbase.block.stair.stairSandStones.*;
import static com.dephoegon.delbase.block.stair.stairSands.*;
import static com.dephoegon.delbase.block.stair.stairSmoothSandStones.*;
import static com.dephoegon.delbase.block.stair.stairTerracotta.*;
import static com.dephoegon.delbase.block.wall.wallChiseledSandStones.*;
import static com.dephoegon.delbase.block.wall.wallConcrete.*;
import static com.dephoegon.delbase.block.wall.wallCutSandStones.*;
import static com.dephoegon.delbase.block.wall.wallSandStones.*;
import static com.dephoegon.delbase.block.wall.wallSands.*;
import static com.dephoegon.delbase.block.wall.wallSmoothSandStones.*;
import static com.dephoegon.delbase.block.wall.wallTerracotta.*;
import static net.minecraft.block.Blocks.*;

public class typeSelector {
    public static ActionResult axis_select(World world, BlockPos blockPos, BlockState state, Block block, PlayerEntity playerEntity, Item inHand) {
        int blockIndex = 4;
        if (block instanceof cutSandStone || state == CUT_SANDSTONE.getDefaultState() || state == CUT_RED_SANDSTONE.getDefaultState()) {
            return ColorLogic(world, blockPos, state, CUT_SANDSTONE.getDefaultState(), CUT_RED_SANDSTONE.getDefaultState(), BLOOD_CUT_SAND_STONE.getDefaultState(), WHITE_CUT_SAND_STONE.getDefaultState(), ORANGE_CUT_SAND_STONE.getDefaultState(), MAGENTA_CUT_SAND_STONE.getDefaultState(), LIGHT_BLUE_CUT_SAND_STONE.getDefaultState(), YELLOW_CUT_SAND_STONE.getDefaultState(), LIME_CUT_SAND_STONE.getDefaultState(), PINK_CUT_SAND_STONE.getDefaultState(), GRAY_CUT_SAND_STONE.getDefaultState(), LIGHT_GRAY_CUT_SAND_STONE.getDefaultState(), CYAN_CUT_SAND_STONE.getDefaultState(), PURPLE_CUT_SAND_STONE.getDefaultState(), BLUE_CUT_SAND_STONE.getDefaultState(), GREEN_CUT_SAND_STONE.getDefaultState(), BROWN_CUT_SAND_STONE.getDefaultState(), BLACK_CUT_SAND_STONE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        return ActionResult.FAIL;
    }
    public static ActionResult slab_select(World world, BlockPos blockPos, BlockState state, Block block, PlayerEntity playerEntity, Item inHand) {
        int blockIndex = 3;
        if (block instanceof chiseledSandStoneSlab) {
            return ColorLogic(world, blockPos, state, CHISELED_SAND_STONE_SLAB.getDefaultState(), RED_CHISELED_SAND_STONE_SLAB.getDefaultState(), BLOOD_CHISELED_SAND_STONE_SLAB.getDefaultState(), WHITE_CHISELED_SAND_STONE_SLAB.getDefaultState(), ORANGE_CHISELED_SAND_STONE_SLAB.getDefaultState(), MAGENTA_CHISELED_SAND_STONE_SLAB.getDefaultState(), LIGHT_BLUE_CHISELED_SAND_STONE_SLAB.getDefaultState(), YELLOW_CHISELED_SAND_STONE_SLAB.getDefaultState(), LIME_CHISELED_SAND_STONE_SLAB.getDefaultState(), PINK_CHISELED_SAND_STONE_SLAB.getDefaultState(), GRAY_CHISELED_SAND_STONE_SLAB.getDefaultState(), LIGHT_GRAY_CHISELED_SAND_STONE_SLAB.getDefaultState(), CYAN_CHISELED_SAND_STONE_SLAB.getDefaultState(), PURPLE_CHISELED_SAND_STONE_SLAB.getDefaultState(), BLUE_CHISELED_SAND_STONE_SLAB.getDefaultState(), GREEN_CHISELED_SAND_STONE_SLAB.getDefaultState(), BROWN_CHISELED_SAND_STONE_SLAB.getDefaultState(), BLACK_CHISELED_SAND_STONE_SLAB.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof chiseledSandStoneSlabEnergy) {
            return ColorLogic(world, blockPos, state, CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), RED_CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), BLOOD_CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), WHITE_CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), ORANGE_CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), MAGENTA_CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), LIGHT_BLUE_CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), YELLOW_CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), LIME_CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), PINK_CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), GRAY_CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), LIGHT_GRAY_CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), CYAN_CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), PURPLE_CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), BLUE_CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), GREEN_CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), BROWN_CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), BLACK_CHISELED_SAND_STONE_SLAB_ENERGY.getDefaultState(), blockIndex, inHand,playerEntity);
        }
        if (block instanceof cutSandStoneSlab || CUT_SANDSTONE_SLAB.getDefaultState() == state || CUT_RED_SANDSTONE_SLAB.getDefaultState() == state) {
            return ColorLogic(world, blockPos, state, CUT_SANDSTONE_SLAB.getDefaultState(), CUT_RED_SANDSTONE_SLAB.getDefaultState(), BLOOD_CUT_SAND_STONE_SLAB.getDefaultState(), WHITE_CUT_SAND_STONE_SLAB.getDefaultState(), ORANGE_CUT_SAND_STONE_SLAB.getDefaultState(), MAGENTA_CUT_SAND_STONE_SLAB.getDefaultState(), LIGHT_BLUE_CUT_SAND_STONE_SLAB.getDefaultState(), YELLOW_CUT_SAND_STONE_SLAB.getDefaultState(), LIME_CUT_SAND_STONE_SLAB.getDefaultState(), PINK_CUT_SAND_STONE_SLAB.getDefaultState(), GRAY_CUT_SAND_STONE_SLAB.getDefaultState(), LIGHT_GRAY_CUT_SAND_STONE_SLAB.getDefaultState(), CYAN_CUT_SAND_STONE_SLAB.getDefaultState(), PURPLE_CUT_SAND_STONE_SLAB.getDefaultState(), BLUE_CUT_SAND_STONE_SLAB.getDefaultState(), GREEN_CUT_SAND_STONE_SLAB.getDefaultState(), BROWN_CUT_SAND_STONE_SLAB.getDefaultState(), BLACK_CUT_SAND_STONE_SLAB.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof cutSandStoneSlabEnergy) {
            return ColorLogic(world, blockPos, state, CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), RED_CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), BLOOD_CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), WHITE_CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), ORANGE_CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), MAGENTA_CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), LIGHT_BLUE_CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), YELLOW_CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), LIME_CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), PINK_CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), GRAY_CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), LIGHT_GRAY_CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), CYAN_CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), PURPLE_CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), BLUE_CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), GREEN_CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), BROWN_CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), BLACK_CUT_SAND_STONE_SLAB_ENERGY.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandSlab) {
            return ColorLogic(world, blockPos, state, SAND_SLAB.getDefaultState(), RED_SAND_SLAB.getDefaultState(), BLOOD_SAND_SLAB.getDefaultState(), WHITE_SAND_SLAB.getDefaultState(), ORANGE_SAND_SLAB.getDefaultState(), MAGENTA_SAND_SLAB.getDefaultState(), LIGHT_BLUE_SAND_SLAB.getDefaultState(), YELLOW_SAND_SLAB.getDefaultState(), LIME_SAND_SLAB.getDefaultState(), PINK_SAND_SLAB.getDefaultState(), GRAY_SAND_SLAB.getDefaultState(), LIGHT_GRAY_SAND_SLAB.getDefaultState(), CYAN_SAND_SLAB.getDefaultState(), PURPLE_SAND_SLAB.getDefaultState(), BLUE_SAND_SLAB.getDefaultState(), GREEN_SAND_SLAB.getDefaultState(), BROWN_SAND_SLAB.getDefaultState(), BLACK_SAND_SLAB.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandSlabEnergy) {
            return ColorLogic(world, blockPos, state, SAND_SLAB_ENERGY.getDefaultState(), RED_SAND_SLAB_ENERGY.getDefaultState(), BLOOD_SAND_SLAB_ENERGY.getDefaultState(), WHITE_SAND_SLAB_ENERGY.getDefaultState(), ORANGE_SAND_SLAB_ENERGY.getDefaultState(), MAGENTA_SAND_SLAB_ENERGY.getDefaultState(), LIGHT_BLUE_SAND_SLAB_ENERGY.getDefaultState(), YELLOW_SAND_SLAB_ENERGY.getDefaultState(), LIME_SAND_SLAB_ENERGY.getDefaultState(), PINK_SAND_SLAB_ENERGY.getDefaultState(), GRAY_SAND_SLAB_ENERGY.getDefaultState(), LIGHT_GRAY_SAND_SLAB_ENERGY.getDefaultState(), CYAN_SAND_SLAB_ENERGY.getDefaultState(), PURPLE_SAND_SLAB_ENERGY.getDefaultState(), BLUE_SAND_SLAB_ENERGY.getDefaultState(), GREEN_SAND_SLAB_ENERGY.getDefaultState(), BROWN_SAND_SLAB_ENERGY.getDefaultState(), BLACK_SAND_SLAB_ENERGY.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandStoneSlab || SANDSTONE_SLAB.getDefaultState() == state || RED_SANDSTONE_SLAB.getDefaultState() == state) {
            return ColorLogic(world, blockPos, state, SANDSTONE_SLAB.getDefaultState(), RED_SANDSTONE_SLAB.getDefaultState(), BLOOD_SAND_STONE_SLAB.getDefaultState(), WHITE_SAND_STONE_SLAB.getDefaultState(), ORANGE_SAND_STONE_SLAB.getDefaultState(), MAGENTA_SAND_STONE_SLAB.getDefaultState(), LIGHT_BLUE_SAND_STONE_SLAB.getDefaultState(), YELLOW_SAND_STONE_SLAB.getDefaultState(), LIME_SAND_STONE_SLAB.getDefaultState(), PINK_SAND_STONE_SLAB.getDefaultState(), GRAY_SAND_STONE_SLAB.getDefaultState(), LIGHT_GRAY_SAND_STONE_SLAB.getDefaultState(), CYAN_SAND_STONE_SLAB.getDefaultState(), PURPLE_SAND_STONE_SLAB.getDefaultState(), BLUE_SAND_STONE_SLAB.getDefaultState(), GREEN_SAND_STONE_SLAB.getDefaultState(), BROWN_SAND_STONE_SLAB.getDefaultState(), BLACK_SAND_STONE_SLAB.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandStoneSlabEnergy) {
            return ColorLogic(world, blockPos, state, SAND_STONE_SLAB_ENERGY.getDefaultState(), RED_SAND_STONE_SLAB_ENERGY.getDefaultState(), BLOOD_SAND_STONE_SLAB_ENERGY.getDefaultState(), WHITE_SAND_STONE_SLAB_ENERGY.getDefaultState(), ORANGE_SAND_STONE_SLAB_ENERGY.getDefaultState(), MAGENTA_SAND_STONE_SLAB_ENERGY.getDefaultState(), LIGHT_BLUE_SAND_STONE_SLAB_ENERGY.getDefaultState(), YELLOW_SAND_STONE_SLAB_ENERGY.getDefaultState(), LIME_SAND_STONE_SLAB_ENERGY.getDefaultState(), PINK_SAND_STONE_SLAB_ENERGY.getDefaultState(), GRAY_SAND_STONE_SLAB_ENERGY.getDefaultState(), LIGHT_GRAY_SAND_STONE_SLAB_ENERGY.getDefaultState(), CYAN_SAND_STONE_SLAB_ENERGY.getDefaultState(), PURPLE_SAND_STONE_SLAB_ENERGY.getDefaultState(), BLUE_SAND_STONE_SLAB_ENERGY.getDefaultState(), GREEN_SAND_STONE_SLAB_ENERGY.getDefaultState(), BROWN_SAND_STONE_SLAB_ENERGY.getDefaultState(), BLACK_SAND_STONE_SLAB_ENERGY.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof smoothSandStoneSlab || SMOOTH_SANDSTONE_SLAB.getDefaultState() == state || SMOOTH_RED_SANDSTONE_SLAB.getDefaultState() == state) {
            return ColorLogic(world, blockPos, state, SMOOTH_SANDSTONE_SLAB.getDefaultState(), SMOOTH_RED_SANDSTONE_SLAB.getDefaultState(), BLOOD_SMOOTH_SAND_STONE_SLAB.getDefaultState(), WHITE_SMOOTH_SAND_STONE_SLAB.getDefaultState(), ORANGE_SMOOTH_SAND_STONE_SLAB.getDefaultState(), MAGENTA_SMOOTH_SAND_STONE_SLAB.getDefaultState(), LIGHT_BLUE_SMOOTH_SAND_STONE_SLAB.getDefaultState(), YELLOW_SMOOTH_SAND_STONE_SLAB.getDefaultState(), LIME_SMOOTH_SAND_STONE_SLAB.getDefaultState(), PINK_SMOOTH_SAND_STONE_SLAB.getDefaultState(), GRAY_SMOOTH_SAND_STONE_SLAB.getDefaultState(), LIGHT_GRAY_SMOOTH_SAND_STONE_SLAB.getDefaultState(), CYAN_SMOOTH_SAND_STONE_SLAB.getDefaultState(), PURPLE_SMOOTH_SAND_STONE_SLAB.getDefaultState(), BLUE_SMOOTH_SAND_STONE_SLAB.getDefaultState(), GREEN_SMOOTH_SAND_STONE_SLAB.getDefaultState(), BROWN_SMOOTH_SAND_STONE_SLAB.getDefaultState(), BLACK_SMOOTH_SAND_STONE_SLAB.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof smoothSandStoneSlabEnergy) {
            return ColorLogic(world, blockPos, state, SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), RED_SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), BLOOD_SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), WHITE_SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), ORANGE_SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), MAGENTA_SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), LIGHT_BLUE_SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), YELLOW_SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), LIME_SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), PINK_SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), GRAY_SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), LIGHT_GRAY_SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), CYAN_SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), PURPLE_SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), BLUE_SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), GREEN_SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), BROWN_SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), BLACK_SMOOTH_SAND_STONE_SLAB_ENERGY.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof terracottaSlab) {
            return ColorLogic(world, blockPos, state, TERRACOTTA_SLAB.getDefaultState(), RED_TERRACOTTA_SLAB.getDefaultState(), null, WHITE_TERRACOTTA_SLAB.getDefaultState(), ORANGE_TERRACOTTA_SLAB.getDefaultState(), MAGENTA_TERRACOTTA_SLAB.getDefaultState(), LIGHT_BLUE_TERRACOTTA_SLAB.getDefaultState(), YELLOW_TERRACOTTA_SLAB.getDefaultState(), LIME_TERRACOTTA_SLAB.getDefaultState(), PINK_TERRACOTTA_SLAB.getDefaultState(), GRAY_TERRACOTTA_SLAB.getDefaultState(), LIGHT_GRAY_TERRACOTTA_SLAB.getDefaultState(), CYAN_TERRACOTTA_SLAB.getDefaultState(), PURPLE_TERRACOTTA_SLAB.getDefaultState(), BLUE_TERRACOTTA_SLAB.getDefaultState(), GREEN_TERRACOTTA_SLAB.getDefaultState(), BROWN_TERRACOTTA_SLAB.getDefaultState(), BLACK_TERRACOTTA_SLAB.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof concreteSlab) {
            return ColorLogic(world, blockPos, state, null, RED_CONCRETE_SLAB.getDefaultState(), null, WHITE_CONCRETE_SLAB.getDefaultState(), ORANGE_CONCRETE_SLAB.getDefaultState(), MAGENTA_CONCRETE_SLAB.getDefaultState(), LIGHT_BLUE_CONCRETE_SLAB.getDefaultState(), YELLOW_CONCRETE_SLAB.getDefaultState(), LIME_CONCRETE_SLAB.getDefaultState(), PINK_CONCRETE_SLAB.getDefaultState(), GRAY_CONCRETE_SLAB.getDefaultState(), LIGHT_GRAY_CONCRETE_SLAB.getDefaultState(), CYAN_CONCRETE_SLAB.getDefaultState(), PURPLE_CONCRETE_SLAB.getDefaultState(), BLUE_CONCRETE_SLAB.getDefaultState(), GREEN_CONCRETE_SLAB.getDefaultState(), BROWN_CONCRETE_SLAB.getDefaultState(), BLACK_CONCRETE_SLAB.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        return ActionResult.FAIL;
    }
    public static ActionResult gen_select(World world, BlockPos blockPos, BlockState state, Block block, PlayerEntity playerEntity, Item inHand) {
        int blockIndex = 5;
        if (getTerracotta_list().contains(state)) {
            return ColorLogic(world, blockPos, state, TERRACOTTA.getDefaultState(), RED_TERRACOTTA.getDefaultState(), null, WHITE_TERRACOTTA.getDefaultState(), ORANGE_TERRACOTTA.getDefaultState(), MAGENTA_TERRACOTTA.getDefaultState(), LIGHT_BLUE_TERRACOTTA.getDefaultState(), YELLOW_TERRACOTTA.getDefaultState(), LIME_TERRACOTTA.getDefaultState(), PINK_TERRACOTTA.getDefaultState(), GRAY_TERRACOTTA.getDefaultState(), LIGHT_GRAY_TERRACOTTA.getDefaultState(), CYAN_TERRACOTTA.getDefaultState(), PURPLE_TERRACOTTA.getDefaultState(), BLUE_TERRACOTTA.getDefaultState(), GREEN_TERRACOTTA.getDefaultState(), BROWN_TERRACOTTA.getDefaultState(), BLACK_TERRACOTTA.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (getConcrete_list().contains(state)) {
            return ColorLogic(world, blockPos, state, null, RED_CONCRETE.getDefaultState(), null, WHITE_CONCRETE.getDefaultState(), ORANGE_CONCRETE.getDefaultState(), MAGENTA_CONCRETE.getDefaultState(), LIGHT_BLUE_CONCRETE.getDefaultState(), YELLOW_CONCRETE.getDefaultState(), LIME_CONCRETE.getDefaultState(), PINK_CONCRETE.getDefaultState(), GRAY_CONCRETE.getDefaultState(), LIGHT_GRAY_CONCRETE.getDefaultState(), CYAN_CONCRETE.getDefaultState(), PURPLE_CONCRETE.getDefaultState(), BLUE_CONCRETE.getDefaultState(), GREEN_CONCRETE.getDefaultState(), BROWN_CONCRETE.getDefaultState(), BLACK_CONCRETE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof chiseledSandStone || state == CHISELED_SANDSTONE.getDefaultState() || state == CHISELED_RED_SANDSTONE.getDefaultState()) {
            return ColorLogic(world, blockPos, state, CHISELED_SANDSTONE.getDefaultState(), CHISELED_RED_SANDSTONE.getDefaultState(), BLOOD_CHISELED_SAND_STONE.getDefaultState(), WHITE_CHISELED_SAND_STONE.getDefaultState(), ORANGE_CHISELED_SAND_STONE.getDefaultState(), MAGENTA_CHISELED_SAND_STONE.getDefaultState(), LIGHT_BLUE_CHISELED_SAND_STONE.getDefaultState(), YELLOW_CHISELED_SAND_STONE.getDefaultState(), LIME_CHISELED_SAND_STONE.getDefaultState(), PINK_CHISELED_SAND_STONE.getDefaultState(), GRAY_CHISELED_SAND_STONE.getDefaultState(), LIGHT_GRAY_CHISELED_SAND_STONE.getDefaultState(), CYAN_CHISELED_SAND_STONE.getDefaultState(), PURPLE_CHISELED_SAND_STONE.getDefaultState(), BLUE_CHISELED_SAND_STONE.getDefaultState(), GREEN_CHISELED_SAND_STONE.getDefaultState(), BROWN_CHISELED_SAND_STONE.getDefaultState(), BLACK_CHISELED_SAND_STONE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof normSandStone || state == SANDSTONE.getDefaultState() || state == RED_SANDSTONE.getDefaultState()) {
            return ColorLogic(world, blockPos, state, SANDSTONE.getDefaultState(), RED_SANDSTONE.getDefaultState(), BLOOD_SAND_STONE.getDefaultState(), WHITE_SAND_STONE.getDefaultState(), ORANGE_SAND_STONE.getDefaultState(), MAGENTA_SAND_STONE.getDefaultState(), LIGHT_BLUE_SAND_STONE.getDefaultState(), YELLOW_SAND_STONE.getDefaultState(), LIME_SAND_STONE.getDefaultState(), PINK_SAND_STONE.getDefaultState(), GRAY_SAND_STONE.getDefaultState(), LIGHT_GRAY_SAND_STONE.getDefaultState(), CYAN_SAND_STONE.getDefaultState(), PURPLE_SAND_STONE.getDefaultState(), BLUE_SAND_STONE.getDefaultState(), GREEN_SAND_STONE.getDefaultState(), BROWN_SAND_STONE.getDefaultState(), BLACK_SAND_STONE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof smoothSandStone || state == SMOOTH_SANDSTONE.getDefaultState() || state == SMOOTH_RED_SANDSTONE.getDefaultState()) {
            return ColorLogic(world, blockPos, state, SMOOTH_SANDSTONE.getDefaultState(), SMOOTH_RED_SANDSTONE.getDefaultState(), BLOOD_SMOOTH_SAND_STONE.getDefaultState(), WHITE_SMOOTH_SAND_STONE.getDefaultState(), ORANGE_SMOOTH_SAND_STONE.getDefaultState(), MAGENTA_SMOOTH_SAND_STONE.getDefaultState(), LIGHT_BLUE_SMOOTH_SAND_STONE.getDefaultState(), YELLOW_SMOOTH_SAND_STONE.getDefaultState(), LIME_SMOOTH_SAND_STONE.getDefaultState(), PINK_SMOOTH_SAND_STONE.getDefaultState(), GRAY_SMOOTH_SAND_STONE.getDefaultState(), LIGHT_GRAY_SMOOTH_SAND_STONE.getDefaultState(), CYAN_SMOOTH_SAND_STONE.getDefaultState(), PURPLE_SMOOTH_SAND_STONE.getDefaultState(), BLUE_SMOOTH_SAND_STONE.getDefaultState(), GREEN_SMOOTH_SAND_STONE.getDefaultState(), BROWN_SMOOTH_SAND_STONE.getDefaultState(), BLACK_SMOOTH_SAND_STONE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        return ActionResult.FAIL;
    }
    public static ActionResult stair_select(World world, BlockPos blockPos, BlockState state, Block block, PlayerEntity playerEntity, Item inHand) {
        int blockIndex = 2;
        if (block instanceof chiseledSandStoneStair) {
            return ColorLogic(world, blockPos, state, CHISELED_SAND_STONE_STAIR.getDefaultState(), RED_CHISELED_SAND_STONE_STAIR.getDefaultState(), BLOOD_CHISELED_SAND_STONE_STAIR.getDefaultState(), WHITE_CHISELED_SAND_STONE_STAIR.getDefaultState(), ORANGE_CHISELED_SAND_STONE_STAIR.getDefaultState(), MAGENTA_CHISELED_SAND_STONE_STAIR.getDefaultState(), LIGHT_BLUE_CHISELED_SAND_STONE_STAIR.getDefaultState(), YELLOW_CHISELED_SAND_STONE_STAIR.getDefaultState(), LIME_CHISELED_SAND_STONE_STAIR.getDefaultState(), PINK_CHISELED_SAND_STONE_STAIR.getDefaultState(), GRAY_CHISELED_SAND_STONE_STAIR.getDefaultState(), LIGHT_GRAY_CHISELED_SAND_STONE_STAIR.getDefaultState(), CYAN_CHISELED_SAND_STONE_STAIR.getDefaultState(), PURPLE_CHISELED_SAND_STONE_STAIR.getDefaultState(), BLUE_CHISELED_SAND_STONE_STAIR.getDefaultState(), GREEN_CHISELED_SAND_STONE_STAIR.getDefaultState(), BROWN_CHISELED_SAND_STONE_STAIR.getDefaultState(), BLACK_CHISELED_SAND_STONE_STAIR.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof cutSandStoneStair) {
            return ColorLogic(world, blockPos, state, CUT_SAND_STONE_STAIR.getDefaultState(), RED_CUT_SAND_STONE_STAIR.getDefaultState(), BLOOD_CUT_SAND_STONE_STAIR.getDefaultState(), WHITE_CUT_SAND_STONE_STAIR.getDefaultState(), ORANGE_CUT_SAND_STONE_STAIR.getDefaultState(), MAGENTA_CUT_SAND_STONE_STAIR.getDefaultState(), LIGHT_BLUE_CUT_SAND_STONE_STAIR.getDefaultState(), YELLOW_CUT_SAND_STONE_STAIR.getDefaultState(), LIME_CUT_SAND_STONE_STAIR.getDefaultState(), PINK_CUT_SAND_STONE_STAIR.getDefaultState(), GRAY_CUT_SAND_STONE_STAIR.getDefaultState(), LIGHT_GRAY_CUT_SAND_STONE_STAIR.getDefaultState(), CYAN_CUT_SAND_STONE_STAIR.getDefaultState(), PURPLE_CUT_SAND_STONE_STAIR.getDefaultState(), BLUE_CUT_SAND_STONE_STAIR.getDefaultState(), GREEN_CUT_SAND_STONE_STAIR.getDefaultState(), BROWN_CUT_SAND_STONE_STAIR.getDefaultState(), BLACK_CUT_SAND_STONE_STAIR.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandStair) {
            return ColorLogic(world, blockPos, state, SAND_STAIR.getDefaultState(), RED_SAND_STAIR.getDefaultState(), BLOOD_SAND_STAIR.getDefaultState(), WHITE_SAND_STAIR.getDefaultState(), ORANGE_SAND_STAIR.getDefaultState(), MAGENTA_SAND_STAIR.getDefaultState(), LIGHT_BLUE_SAND_STAIR.getDefaultState(), YELLOW_SAND_STAIR.getDefaultState(), LIME_SAND_STAIR.getDefaultState(), PINK_SAND_STAIR.getDefaultState(), GRAY_SAND_STAIR.getDefaultState(), LIGHT_GRAY_SAND_STAIR.getDefaultState(), CYAN_SAND_STAIR.getDefaultState(), PURPLE_SAND_STAIR.getDefaultState(), BLUE_SAND_STAIR.getDefaultState(), GREEN_SAND_STAIR.getDefaultState(), BROWN_SAND_STAIR.getDefaultState(), BLACK_SAND_STAIR.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandStoneStair || state == SANDSTONE_STAIRS.getDefaultState() || state == RED_SANDSTONE_STAIRS.getDefaultState()) {
            return ColorLogic(world, blockPos, state, SANDSTONE_STAIRS.getDefaultState(), RED_SANDSTONE_STAIRS.getDefaultState(), BLOOD_SAND_STONE_STAIR.getDefaultState(), WHITE_SAND_STONE_STAIR.getDefaultState(), ORANGE_SAND_STONE_STAIR.getDefaultState(), MAGENTA_SAND_STONE_STAIR.getDefaultState(), LIGHT_BLUE_SAND_STONE_STAIR.getDefaultState(), YELLOW_SAND_STONE_STAIR.getDefaultState(), LIME_SAND_STONE_STAIR.getDefaultState(), PINK_SAND_STONE_STAIR.getDefaultState(), GRAY_SAND_STONE_STAIR.getDefaultState(), LIGHT_GRAY_SAND_STONE_STAIR.getDefaultState(), CYAN_SAND_STONE_STAIR.getDefaultState(), PURPLE_SAND_STONE_STAIR.getDefaultState(), BLUE_SAND_STONE_STAIR.getDefaultState(), GREEN_SAND_STONE_STAIR.getDefaultState(), BROWN_SAND_STONE_STAIR.getDefaultState(), BLACK_SAND_STONE_STAIR.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof smoothSandStoneStair || state == SMOOTH_SANDSTONE_STAIRS.getDefaultState() || state == SMOOTH_RED_SANDSTONE_STAIRS.getDefaultState()) {
            return ColorLogic(world, blockPos, state, SMOOTH_SANDSTONE_STAIRS.getDefaultState(), SMOOTH_RED_SANDSTONE_STAIRS.getDefaultState(), BLOOD_SMOOTH_SAND_STONE_STAIR.getDefaultState(), WHITE_SMOOTH_SAND_STONE_STAIR.getDefaultState(), ORANGE_SMOOTH_SAND_STONE_STAIR.getDefaultState(), MAGENTA_SMOOTH_SAND_STONE_STAIR.getDefaultState(), LIGHT_BLUE_SMOOTH_SAND_STONE_STAIR.getDefaultState(), YELLOW_SMOOTH_SAND_STONE_STAIR.getDefaultState(), LIME_SMOOTH_SAND_STONE_STAIR.getDefaultState(), PINK_SMOOTH_SAND_STONE_STAIR.getDefaultState(), GRAY_SMOOTH_SAND_STONE_STAIR.getDefaultState(), LIGHT_GRAY_SMOOTH_SAND_STONE_STAIR.getDefaultState(), CYAN_SMOOTH_SAND_STONE_STAIR.getDefaultState(), PURPLE_SMOOTH_SAND_STONE_STAIR.getDefaultState(), BLUE_SMOOTH_SAND_STONE_STAIR.getDefaultState(), GREEN_SMOOTH_SAND_STONE_STAIR.getDefaultState(), BROWN_SMOOTH_SAND_STONE_STAIR.getDefaultState(), BLACK_SMOOTH_SAND_STONE_STAIR.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof terracottaStair) {
            return ColorLogic(world, blockPos, state, TERRACOTTA_STAIR.getDefaultState(), RED_TERRACOTTA_STAIR.getDefaultState(), null, WHITE_TERRACOTTA_STAIR.getDefaultState(), ORANGE_TERRACOTTA_STAIR.getDefaultState(), MAGENTA_TERRACOTTA_STAIR.getDefaultState(), LIGHT_BLUE_TERRACOTTA_STAIR.getDefaultState(), YELLOW_TERRACOTTA_STAIR.getDefaultState(), LIME_TERRACOTTA_STAIR.getDefaultState(), PINK_TERRACOTTA_STAIR.getDefaultState(), GRAY_TERRACOTTA_STAIR.getDefaultState(), LIGHT_GRAY_TERRACOTTA_STAIR.getDefaultState(), CYAN_TERRACOTTA_STAIR.getDefaultState(), PURPLE_TERRACOTTA_STAIR.getDefaultState(), BLUE_TERRACOTTA_STAIR.getDefaultState(), GREEN_TERRACOTTA_STAIR.getDefaultState(), BROWN_TERRACOTTA_STAIR.getDefaultState(), BLACK_TERRACOTTA_STAIR.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof concreteStair) {
            return  ColorLogic(world, blockPos, state, null, RED_CONCRETE_STAIR.getDefaultState(), null, WHITE_CONCRETE_STAIR.getDefaultState(), ORANGE_CONCRETE_STAIR.getDefaultState(), MAGENTA_CONCRETE_STAIR.getDefaultState(), LIGHT_BLUE_CONCRETE_STAIR.getDefaultState(), YELLOW_CONCRETE_STAIR.getDefaultState(), LIME_CONCRETE_STAIR.getDefaultState(), PINK_CONCRETE_STAIR.getDefaultState(), GRAY_CONCRETE_STAIR.getDefaultState(), LIGHT_GRAY_CONCRETE_STAIR.getDefaultState(), CYAN_CONCRETE_STAIR.getDefaultState(), PURPLE_CONCRETE_STAIR.getDefaultState(), BLUE_CONCRETE_STAIR.getDefaultState(), GREEN_CONCRETE_STAIR.getDefaultState(), BROWN_CONCRETE_STAIR.getDefaultState(), BLACK_CONCRETE_STAIR.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        return ActionResult.FAIL;
    }
    public static ActionResult wall_select(World world, BlockPos blockPos, BlockState state, Block block, PlayerEntity playerEntity, Item inHand) {
        int blockIndex = 1;
        if (block instanceof chiseledSandStoneWall) {
            return ColorLogic(world, blockPos, state, CHISELED_SAND_STONE_WALL.getDefaultState(), RED_CHISELED_SAND_STONE_WALL.getDefaultState(), BLOOD_CHISELED_SAND_STONE_WALL.getDefaultState(), WHITE_CHISELED_SAND_STONE_WALL.getDefaultState(), ORANGE_CHISELED_SAND_STONE_WALL.getDefaultState(), MAGENTA_CHISELED_SAND_STONE_WALL.getDefaultState(), LIGHT_BLUE_CHISELED_SAND_STONE_WALL.getDefaultState(), YELLOW_CHISELED_SAND_STONE_WALL.getDefaultState(), LIME_CHISELED_SAND_STONE_WALL.getDefaultState(), PINK_CHISELED_SAND_STONE_WALL.getDefaultState(), GRAY_CHISELED_SAND_STONE_WALL.getDefaultState(), LIGHT_GRAY_CHISELED_SAND_STONE_WALL.getDefaultState(), CYAN_CHISELED_SAND_STONE_WALL.getDefaultState(), PURPLE_CHISELED_SAND_STONE_WALL.getDefaultState(), BLUE_CHISELED_SAND_STONE_WALL.getDefaultState(), GREEN_CHISELED_SAND_STONE_WALL.getDefaultState(), BROWN_CHISELED_SAND_STONE_WALL.getDefaultState(), BLACK_CHISELED_SAND_STONE_WALL.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof cutSandStoneWall) {
            return ColorLogic(world, blockPos, state, CUT_SAND_STONE_WALL.getDefaultState(), RED_CUT_SAND_STONE_WALL.getDefaultState(), BLOOD_CUT_SAND_STONE_WALL.getDefaultState(), WHITE_CUT_SAND_STONE_WALL.getDefaultState(), ORANGE_CUT_SAND_STONE_WALL.getDefaultState(), MAGENTA_CUT_SAND_STONE_WALL.getDefaultState(), LIGHT_BLUE_CUT_SAND_STONE_WALL.getDefaultState(), YELLOW_CUT_SAND_STONE_WALL.getDefaultState(), LIME_CUT_SAND_STONE_WALL.getDefaultState(), PINK_CUT_SAND_STONE_WALL.getDefaultState(), GRAY_CUT_SAND_STONE_WALL.getDefaultState(), LIGHT_GRAY_CUT_SAND_STONE_WALL.getDefaultState(), CYAN_CUT_SAND_STONE_WALL.getDefaultState(), PURPLE_CUT_SAND_STONE_WALL.getDefaultState(), BLUE_CUT_SAND_STONE_WALL.getDefaultState(), GREEN_CUT_SAND_STONE_WALL.getDefaultState(), BROWN_CUT_SAND_STONE_WALL.getDefaultState(), BLACK_CUT_SAND_STONE_WALL.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandStoneWall || state == SANDSTONE_WALL.getDefaultState() || state == RED_SANDSTONE_WALL.getDefaultState()) {
            return ColorLogic(world, blockPos, state, SANDSTONE_WALL.getDefaultState(), RED_SANDSTONE_WALL.getDefaultState(), BLOOD_SAND_STONE_WALL.getDefaultState(), WHITE_SAND_STONE_WALL.getDefaultState(), ORANGE_SAND_STONE_WALL.getDefaultState(), MAGENTA_SAND_STONE_WALL.getDefaultState(), LIGHT_BLUE_SAND_STONE_WALL.getDefaultState(), YELLOW_SAND_STONE_WALL.getDefaultState(), LIME_SAND_STONE_WALL.getDefaultState(), PINK_SAND_STONE_WALL.getDefaultState(), GRAY_SAND_STONE_WALL.getDefaultState(), LIGHT_GRAY_SAND_STONE_WALL.getDefaultState(), CYAN_SAND_STONE_WALL.getDefaultState(), PURPLE_SAND_STONE_WALL.getDefaultState(), BLUE_SAND_STONE_WALL.getDefaultState(), GREEN_SAND_STONE_WALL.getDefaultState(), BROWN_SAND_STONE_WALL.getDefaultState(), BLACK_SAND_STONE_WALL.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandWall) {
            return ColorLogic(world, blockPos, state, SAND_WALL.getDefaultState(), RED_SAND_WALL.getDefaultState(), BLOOD_SAND_WALL.getDefaultState(), WHITE_SAND_WALL.getDefaultState(), ORANGE_SAND_WALL.getDefaultState(), MAGENTA_SAND_WALL.getDefaultState(), LIGHT_BLUE_SAND_WALL.getDefaultState(), YELLOW_SAND_WALL.getDefaultState(), LIME_SAND_WALL.getDefaultState(), PINK_SAND_WALL.getDefaultState(), GRAY_SAND_WALL.getDefaultState(), LIGHT_GRAY_SAND_WALL.getDefaultState(), CYAN_SAND_WALL.getDefaultState(), PURPLE_SAND_WALL.getDefaultState(), BLUE_SAND_WALL.getDefaultState(), GREEN_SAND_WALL.getDefaultState(), BROWN_SAND_WALL.getDefaultState(), BLACK_SAND_WALL.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof smoothSandStoneWall) {
            return ColorLogic(world, blockPos, state, SMOOTH_SAND_STONE_WALL.getDefaultState(), RED_SMOOTH_SAND_STONE_WALL.getDefaultState(), BLOOD_SMOOTH_SAND_STONE_WALL.getDefaultState(), WHITE_SMOOTH_SAND_STONE_WALL.getDefaultState(), ORANGE_SMOOTH_SAND_STONE_WALL.getDefaultState(), MAGENTA_SMOOTH_SAND_STONE_WALL.getDefaultState(), LIGHT_BLUE_SMOOTH_SAND_STONE_WALL.getDefaultState(), YELLOW_SMOOTH_SAND_STONE_WALL.getDefaultState(), LIME_SMOOTH_SAND_STONE_WALL.getDefaultState(), PINK_SMOOTH_SAND_STONE_WALL.getDefaultState(), GRAY_SMOOTH_SAND_STONE_WALL.getDefaultState(), LIGHT_GRAY_SMOOTH_SAND_STONE_WALL.getDefaultState(), CYAN_SMOOTH_SAND_STONE_WALL.getDefaultState(), PURPLE_SMOOTH_SAND_STONE_WALL.getDefaultState(), BLUE_SMOOTH_SAND_STONE_WALL.getDefaultState(), GREEN_SMOOTH_SAND_STONE_WALL.getDefaultState(), BROWN_SMOOTH_SAND_STONE_WALL.getDefaultState(), BLACK_SMOOTH_SAND_STONE_WALL.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof terracottaWall) {
            return ColorLogic(world, blockPos, state, TERRACOTTA_WALL.getDefaultState(), RED_TERRACOTTA_WALL.getDefaultState(), null, WHITE_TERRACOTTA_WALL.getDefaultState(), ORANGE_TERRACOTTA_WALL.getDefaultState(), MAGENTA_TERRACOTTA_WALL.getDefaultState(), LIGHT_BLUE_TERRACOTTA_WALL.getDefaultState(), YELLOW_TERRACOTTA_WALL.getDefaultState(), LIME_TERRACOTTA_WALL.getDefaultState(), PINK_TERRACOTTA_WALL.getDefaultState(), GRAY_TERRACOTTA_WALL.getDefaultState(), LIGHT_GRAY_TERRACOTTA_WALL.getDefaultState(), CYAN_TERRACOTTA_WALL.getDefaultState(), PURPLE_TERRACOTTA_WALL.getDefaultState(), BLUE_TERRACOTTA_WALL.getDefaultState(), GREEN_TERRACOTTA_WALL.getDefaultState(), BROWN_TERRACOTTA_WALL.getDefaultState(), BLACK_TERRACOTTA_WALL.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof concreteWall) {
            return ColorLogic(world, blockPos, state, null, RED_CONCRETE_WALL.getDefaultState(), null, WHITE_CONCRETE_WALL.getDefaultState(), ORANGE_CONCRETE_WALL.getDefaultState(), MAGENTA_CONCRETE_WALL.getDefaultState(), LIGHT_BLUE_CONCRETE_WALL.getDefaultState(), YELLOW_CONCRETE_WALL.getDefaultState(), LIME_CONCRETE_WALL.getDefaultState(), PINK_CONCRETE_WALL.getDefaultState(), GRAY_CONCRETE_WALL.getDefaultState(), LIGHT_GRAY_CONCRETE_WALL.getDefaultState(), CYAN_CONCRETE_WALL.getDefaultState(), PURPLE_CONCRETE_WALL.getDefaultState(), BLUE_CONCRETE_WALL.getDefaultState(), GREEN_CONCRETE_WALL.getDefaultState(), BROWN_CONCRETE_WALL.getDefaultState(), BLACK_CONCRETE_WALL.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        return ActionResult.FAIL;
    }
    public static ActionResult fence_select(World world, BlockPos blockPos, BlockState state, Block block, PlayerEntity playerEntity, Item inHand) {
        int blockIndex = 6;
        if (block instanceof chiseledSandStoneFence) {
            return ColorLogic(world, blockPos, state, CHISELED_SAND_STONE_FENCE.getDefaultState(),RED_CHISELED_SAND_STONE_FENCE.getDefaultState(), BLOOD_CHISELED_SAND_STONE_FENCE.getDefaultState(), WHITE_CHISELED_SAND_STONE_FENCE.getDefaultState(), ORANGE_CHISELED_SAND_STONE_FENCE.getDefaultState(), MAGENTA_CHISELED_SAND_STONE_FENCE.getDefaultState(), LIGHT_BLUE_CHISELED_SAND_STONE_FENCE.getDefaultState(), YELLOW_CHISELED_SAND_STONE_FENCE.getDefaultState(), LIME_CHISELED_SAND_STONE_FENCE.getDefaultState(), PINK_CHISELED_SAND_STONE_FENCE.getDefaultState(), GRAY_CHISELED_SAND_STONE_FENCE.getDefaultState(), LIGHT_GRAY_CHISELED_SAND_STONE_FENCE.getDefaultState(), CYAN_CHISELED_SAND_STONE_FENCE.getDefaultState(), PURPLE_CHISELED_SAND_STONE_FENCE.getDefaultState(), BLUE_CHISELED_SAND_STONE_FENCE.getDefaultState(), GREEN_CHISELED_SAND_STONE_FENCE.getDefaultState(), BROWN_CHISELED_SAND_STONE_FENCE.getDefaultState(), BLACK_CHISELED_SAND_STONE_FENCE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof concreteFence) {
            return ColorLogic(world, blockPos, state, null, RED_CONCRETE_FENCE.getDefaultState(), null, WHITE_CONCRETE_FENCE.getDefaultState(), ORANGE_CONCRETE_FENCE.getDefaultState(), MAGENTA_CONCRETE_FENCE.getDefaultState(), LIGHT_BLUE_CONCRETE_FENCE.getDefaultState(), YELLOW_CONCRETE_FENCE.getDefaultState(), LIME_CONCRETE_FENCE.getDefaultState(), PINK_CONCRETE_FENCE.getDefaultState(), GRAY_CONCRETE_FENCE.getDefaultState(), LIGHT_GRAY_CONCRETE_FENCE.getDefaultState(), CYAN_CONCRETE_FENCE.getDefaultState(), PURPLE_CONCRETE_FENCE.getDefaultState(), BLUE_CONCRETE_FENCE.getDefaultState(), GREEN_CONCRETE_FENCE.getDefaultState(), BROWN_CONCRETE_FENCE.getDefaultState(), BLACK_CONCRETE_FENCE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof cutSandStoneFence) {
            return ColorLogic(world, blockPos, state, CUT_SAND_STONE_FENCE.getDefaultState(), RED_CUT_SAND_STONE_FENCE.getDefaultState(), BLOOD_CUT_SAND_STONE_FENCE.getDefaultState(), WHITE_CUT_SAND_STONE_FENCE.getDefaultState(), ORANGE_CUT_SAND_STONE_FENCE.getDefaultState(), MAGENTA_CUT_SAND_STONE_FENCE.getDefaultState(), LIGHT_BLUE_CUT_SAND_STONE_FENCE.getDefaultState(), YELLOW_CUT_SAND_STONE_FENCE.getDefaultState(), LIME_CUT_SAND_STONE_FENCE.getDefaultState(), PINK_CUT_SAND_STONE_FENCE.getDefaultState(), GRAY_CUT_SAND_STONE_FENCE.getDefaultState(), LIGHT_GRAY_CUT_SAND_STONE_FENCE.getDefaultState(), CYAN_CUT_SAND_STONE_FENCE.getDefaultState(), PURPLE_CUT_SAND_STONE_FENCE.getDefaultState(), BLUE_CUT_SAND_STONE_FENCE.getDefaultState(), GREEN_CUT_SAND_STONE_FENCE.getDefaultState(), BROWN_CUT_SAND_STONE_FENCE.getDefaultState(), BLACK_CUT_SAND_STONE_FENCE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandFence) {
            return ColorLogic(world, blockPos, state, SAND_FENCE.getDefaultState(), RED_SAND_FENCE.getDefaultState(), BLOOD_SAND_FENCE.getDefaultState(), WHITE_SAND_FENCE.getDefaultState(), ORANGE_SAND_FENCE.getDefaultState(), MAGENTA_SAND_FENCE.getDefaultState(), LIGHT_BLUE_SAND_FENCE.getDefaultState(), YELLOW_SAND_FENCE.getDefaultState(), LIME_SAND_FENCE.getDefaultState(), PINK_SAND_FENCE.getDefaultState(), GRAY_SAND_FENCE.getDefaultState(), LIGHT_GRAY_SAND_FENCE.getDefaultState(), CYAN_SAND_FENCE.getDefaultState(), PURPLE_SAND_FENCE.getDefaultState(), BLUE_SAND_FENCE.getDefaultState(), GREEN_SAND_FENCE.getDefaultState(), BROWN_SAND_FENCE.getDefaultState(), BLACK_SAND_FENCE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandStoneFence) {
            return ColorLogic(world, blockPos, state, SAND_STONE_FENCE.getDefaultState(), RED_SAND_STONE_FENCE.getDefaultState(), BLOOD_SAND_STONE_FENCE.getDefaultState(), WHITE_SAND_STONE_FENCE.getDefaultState(), ORANGE_SAND_STONE_FENCE.getDefaultState(), MAGENTA_SAND_STONE_FENCE.getDefaultState(), LIGHT_BLUE_SAND_STONE_FENCE.getDefaultState(), YELLOW_SAND_STONE_FENCE.getDefaultState(), LIME_SAND_STONE_FENCE.getDefaultState(), PINK_SAND_STONE_FENCE.getDefaultState(), GRAY_SAND_STONE_FENCE.getDefaultState(), LIGHT_GRAY_SAND_STONE_FENCE.getDefaultState(), CYAN_SAND_STONE_FENCE.getDefaultState(), PURPLE_SAND_STONE_FENCE.getDefaultState(), BLUE_SAND_STONE_FENCE.getDefaultState(), GREEN_SAND_STONE_FENCE.getDefaultState(), BROWN_SAND_STONE_FENCE.getDefaultState(), BLACK_SAND_STONE_FENCE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof smoothSandStoneFence) {
            return ColorLogic(world, blockPos, state, SMOOTH_SAND_STONE_FENCE.getDefaultState(), RED_SMOOTH_SAND_STONE_FENCE.getDefaultState(), BLOOD_SMOOTH_SAND_STONE_FENCE.getDefaultState(), WHITE_SMOOTH_SAND_STONE_FENCE.getDefaultState(), ORANGE_SMOOTH_SAND_STONE_FENCE.getDefaultState(), MAGENTA_SMOOTH_SAND_STONE_FENCE.getDefaultState(), LIGHT_BLUE_SMOOTH_SAND_STONE_FENCE.getDefaultState(), YELLOW_SMOOTH_SAND_STONE_FENCE.getDefaultState(), LIME_SMOOTH_SAND_STONE_FENCE.getDefaultState(), PINK_SMOOTH_SAND_STONE_FENCE.getDefaultState(), GRAY_SMOOTH_SAND_STONE_FENCE.getDefaultState(), LIGHT_GRAY_SMOOTH_SAND_STONE_FENCE.getDefaultState(), CYAN_SMOOTH_SAND_STONE_FENCE.getDefaultState(), PURPLE_SMOOTH_SAND_STONE_FENCE.getDefaultState(), BLUE_SMOOTH_SAND_STONE_FENCE.getDefaultState(), GREEN_SMOOTH_SAND_STONE_FENCE.getDefaultState(), BROWN_SMOOTH_SAND_STONE_FENCE.getDefaultState(), BLACK_SMOOTH_SAND_STONE_FENCE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof terracottaFence) {
            return ColorLogic(world, blockPos, state, TERRACOTTA_FENCE.getDefaultState(), RED_TERRACOTTA_FENCE.getDefaultState(), null, WHITE_TERRACOTTA_FENCE.getDefaultState(), ORANGE_TERRACOTTA_FENCE.getDefaultState(), MAGENTA_TERRACOTTA_FENCE.getDefaultState(), LIGHT_BLUE_TERRACOTTA_FENCE.getDefaultState(), YELLOW_TERRACOTTA_FENCE.getDefaultState(), LIME_TERRACOTTA_FENCE.getDefaultState(), PINK_TERRACOTTA_FENCE.getDefaultState(), GRAY_TERRACOTTA_FENCE.getDefaultState(), LIGHT_GRAY_TERRACOTTA_FENCE.getDefaultState(), CYAN_TERRACOTTA_FENCE.getDefaultState(), PURPLE_TERRACOTTA_FENCE.getDefaultState(), BLUE_TERRACOTTA_FENCE.getDefaultState(), GREEN_TERRACOTTA_FENCE.getDefaultState(), BROWN_TERRACOTTA_FENCE.getDefaultState(), BLACK_TERRACOTTA_FENCE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        return ActionResult.FAIL;
    }
    public static ActionResult fenceGate_select(World world, BlockPos blockPos, BlockState state, Block block, PlayerEntity playerEntity, Item inHand) {
        int blockIndex = 7;
        if (block instanceof chiseledSandStoneFenceGate) {
            return ColorLogic(world, blockPos, state, CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), RED_CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), BLOOD_CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), WHITE_CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), ORANGE_CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), MAGENTA_CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), LIGHT_BLUE_CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), YELLOW_CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), LIME_CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), PINK_CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), GRAY_CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), LIGHT_GRAY_CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), CYAN_CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), PURPLE_CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), BLUE_CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), GREEN_CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), BROWN_CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), BLACK_CHISELED_SAND_STONE_FENCE_GATE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof concreteFenceGate) {
            return ColorLogic(world, blockPos, state, null, RED_CONCRETE_FENCE_GATE.getDefaultState(), null, WHITE_CONCRETE_FENCE_GATE.getDefaultState(), ORANGE_CONCRETE_FENCE_GATE.getDefaultState(), MAGENTA_CONCRETE_FENCE_GATE.getDefaultState(), LIGHT_BLUE_CONCRETE_FENCE_GATE.getDefaultState(), YELLOW_CONCRETE_FENCE_GATE.getDefaultState(), LIME_CONCRETE_FENCE_GATE.getDefaultState(), PINK_CONCRETE_FENCE_GATE.getDefaultState(), GRAY_CONCRETE_FENCE_GATE.getDefaultState(), LIGHT_GRAY_CONCRETE_FENCE_GATE.getDefaultState(), CYAN_CONCRETE_FENCE_GATE.getDefaultState(), PURPLE_CONCRETE_FENCE_GATE.getDefaultState(), BLUE_CONCRETE_FENCE_GATE.getDefaultState(), GREEN_CONCRETE_FENCE_GATE.getDefaultState(), BROWN_CONCRETE_FENCE_GATE.getDefaultState(), BLACK_CONCRETE_FENCE_GATE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof cutSandStoneFenceGate) {
            return ColorLogic(world, blockPos, state, CUT_SAND_STONE_FENCE_GATE.getDefaultState(), RED_CUT_SAND_STONE_FENCE_GATE.getDefaultState(), BLOOD_CUT_SAND_STONE_FENCE_GATE.getDefaultState(), WHITE_CUT_SAND_STONE_FENCE_GATE.getDefaultState(), ORANGE_CUT_SAND_STONE_FENCE_GATE.getDefaultState(), MAGENTA_CUT_SAND_STONE_FENCE_GATE.getDefaultState(), LIGHT_BLUE_CUT_SAND_STONE_FENCE_GATE.getDefaultState(), YELLOW_CUT_SAND_STONE_FENCE_GATE.getDefaultState(), LIME_CUT_SAND_STONE_FENCE_GATE.getDefaultState(), PINK_CUT_SAND_STONE_FENCE_GATE.getDefaultState(), GRAY_CUT_SAND_STONE_FENCE_GATE.getDefaultState(), LIGHT_GRAY_CUT_SAND_STONE_FENCE_GATE.getDefaultState(), CYAN_CUT_SAND_STONE_FENCE_GATE.getDefaultState(), PURPLE_CUT_SAND_STONE_FENCE_GATE.getDefaultState(), BLUE_CUT_SAND_STONE_FENCE_GATE.getDefaultState(), GREEN_CUT_SAND_STONE_FENCE_GATE.getDefaultState(), BROWN_CUT_SAND_STONE_FENCE_GATE.getDefaultState(), BLACK_CUT_SAND_STONE_FENCE_GATE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandFenceGate) {
            return ColorLogic(world, blockPos, state, SAND_FENCE_GATE.getDefaultState(), RED_SAND_FENCE_GATE.getDefaultState(), BLOOD_SAND_FENCE_GATE.getDefaultState(), WHITE_SAND_FENCE_GATE.getDefaultState(), ORANGE_SAND_FENCE_GATE.getDefaultState(), MAGENTA_SAND_FENCE_GATE.getDefaultState(), LIGHT_BLUE_SAND_FENCE_GATE.getDefaultState(), YELLOW_SAND_FENCE_GATE.getDefaultState(), LIME_SAND_FENCE_GATE.getDefaultState(), PINK_SAND_FENCE_GATE.getDefaultState(), GRAY_SAND_FENCE_GATE.getDefaultState(), LIGHT_GRAY_SAND_FENCE_GATE.getDefaultState(), CYAN_SAND_FENCE_GATE.getDefaultState(), PURPLE_SAND_FENCE_GATE.getDefaultState(), BLUE_SAND_FENCE_GATE.getDefaultState(), GREEN_SAND_FENCE_GATE.getDefaultState(), BROWN_SAND_FENCE_GATE.getDefaultState(), BLACK_SAND_FENCE_GATE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof sandStoneFenceGate) {
            return ColorLogic(world, blockPos, state, SAND_STONE_FENCE_GATE.getDefaultState(), RED_SAND_STONE_FENCE_GATE.getDefaultState(), BLOOD_SAND_STONE_FENCE_GATE.getDefaultState(), WHITE_SAND_STONE_FENCE_GATE.getDefaultState(), ORANGE_SAND_STONE_FENCE_GATE.getDefaultState(), MAGENTA_SAND_STONE_FENCE_GATE.getDefaultState(), LIGHT_BLUE_SAND_STONE_FENCE_GATE.getDefaultState(), YELLOW_SAND_STONE_FENCE_GATE.getDefaultState(), LIME_SAND_STONE_FENCE_GATE.getDefaultState(), PINK_SAND_STONE_FENCE_GATE.getDefaultState(), GRAY_SAND_STONE_FENCE_GATE.getDefaultState(), LIGHT_GRAY_SAND_STONE_FENCE_GATE.getDefaultState(), CYAN_SAND_STONE_FENCE_GATE.getDefaultState(), PURPLE_SAND_STONE_FENCE_GATE.getDefaultState(), BLUE_SAND_STONE_FENCE_GATE.getDefaultState(), GREEN_SAND_STONE_FENCE_GATE.getDefaultState(), BROWN_SAND_STONE_FENCE_GATE.getDefaultState(), BLACK_SAND_STONE_FENCE_GATE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof smoothSandStoneFenceGate) {
            return ColorLogic(world, blockPos, state, SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), RED_SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), BLOOD_SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), WHITE_SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), ORANGE_SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), MAGENTA_SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), LIGHT_BLUE_SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), YELLOW_SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), LIME_SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), PINK_SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), GRAY_SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), LIGHT_GRAY_SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), CYAN_SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), PURPLE_SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), BLUE_SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), GREEN_SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), BROWN_SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), BLACK_SMOOTH_SAND_STONE_FENCE_GATE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (block instanceof terracottaFenceGate) {
            return ColorLogic(world, blockPos, state, TERRACOTTA_FENCE_GATE.getDefaultState(), RED_TERRACOTTA_FENCE_GATE.getDefaultState(), null, WHITE_TERRACOTTA_FENCE_GATE.getDefaultState(), ORANGE_TERRACOTTA_FENCE_GATE.getDefaultState(), MAGENTA_TERRACOTTA_FENCE_GATE.getDefaultState(), LIGHT_BLUE_TERRACOTTA_FENCE_GATE.getDefaultState(), YELLOW_TERRACOTTA_FENCE_GATE.getDefaultState(), LIME_TERRACOTTA_FENCE_GATE.getDefaultState(), PINK_TERRACOTTA_FENCE_GATE.getDefaultState(), GRAY_TERRACOTTA_FENCE_GATE.getDefaultState(), LIGHT_GRAY_TERRACOTTA_FENCE_GATE.getDefaultState(), CYAN_TERRACOTTA_FENCE_GATE.getDefaultState(), PURPLE_TERRACOTTA_FENCE_GATE.getDefaultState(), BLUE_TERRACOTTA_FENCE_GATE.getDefaultState(), GREEN_TERRACOTTA_FENCE_GATE.getDefaultState(), BROWN_TERRACOTTA_FENCE_GATE.getDefaultState(), BLACK_TERRACOTTA_FENCE_GATE.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        return ActionResult.FAIL;
    }
    public static ActionResult grav_select(World world, BlockPos blockPos, BlockState state, Block block, PlayerEntity playerEntity, Item inHand) {
        int blockIndex = 5;
        if (block instanceof sandBlock || getSand_list().contains(state)) {
            return ColorLogic(world, blockPos, state, SAND.getDefaultState(), RED_SAND.getDefaultState(), BLOOD_SAND.getDefaultState(), WHITE_SAND.getDefaultState(), ORANGE_SAND.getDefaultState(), MAGENTA_SAND.getDefaultState(), LIGHT_BLUE_SAND.getDefaultState(), YELLOW_SAND.getDefaultState(), LIME_SAND.getDefaultState(), PINK_SAND.getDefaultState(), GRAY_SAND.getDefaultState(), LIGHT_GRAY_SAND.getDefaultState(), CYAN_SAND.getDefaultState(), PURPLE_SAND.getDefaultState(), BLUE_SAND.getDefaultState(), GREEN_SAND.getDefaultState(), BROWN_SAND.getDefaultState(), BLACK_SAND.getDefaultState(),blockIndex, inHand, playerEntity);
        }
        if (block instanceof solidSandBlock) {
            return ColorLogic(world, blockPos, state, SOLID_SAND.getDefaultState(), RED_SOLID_SAND.getDefaultState(), BLOOD_SOLID_SAND.getDefaultState(), WHITE_SOLID_SAND.getDefaultState(), ORANGE_SOLID_SAND.getDefaultState(), MAGENTA_SOLID_SAND.getDefaultState(), LIGHT_BLUE_SOLID_SAND.getDefaultState(), YELLOW_SOLID_SAND.getDefaultState(), LIME_SOLID_SAND.getDefaultState(), PINK_SOLID_SAND.getDefaultState(), GRAY_SOLID_SAND.getDefaultState(), LIGHT_GRAY_SOLID_SAND.getDefaultState(), CYAN_SOLID_SAND.getDefaultState(), PURPLE_SOLID_SAND.getDefaultState(), BLUE_SOLID_SAND.getDefaultState(), GREEN_SOLID_SAND.getDefaultState(), BROWN_SOLID_SAND.getDefaultState(), BLACK_SOLID_SAND.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        if (getConcretePowder_list().contains(state)) {
            return ColorLogic(world, blockPos, state, null, RED_CONCRETE_POWDER.getDefaultState(), null, WHITE_CONCRETE_POWDER.getDefaultState(), ORANGE_CONCRETE_POWDER.getDefaultState(), MAGENTA_CONCRETE_POWDER.getDefaultState(), LIGHT_BLUE_CONCRETE_POWDER.getDefaultState(), YELLOW_CONCRETE_POWDER.getDefaultState(), LIME_CONCRETE_POWDER.getDefaultState(), PINK_CONCRETE_POWDER.getDefaultState(), GRAY_CONCRETE_POWDER.getDefaultState(), LIGHT_GRAY_CONCRETE_POWDER.getDefaultState(), CYAN_CONCRETE_POWDER.getDefaultState(), PURPLE_CONCRETE_POWDER.getDefaultState(), BLUE_CONCRETE_POWDER.getDefaultState(), GREEN_CONCRETE_POWDER.getDefaultState(), BROWN_CONCRETE_POWDER.getDefaultState(), BLACK_CONCRETE_POWDER.getDefaultState(), blockIndex, inHand, playerEntity);
        }
        return ActionResult.FAIL;
    }
}